config/routes.rb
Rails.application.routes.draw do
resources :selections
    
  get '/home' => 'welcome#home'

  get '/choosestation' => 'welcome#radioselect'

  get 'welcome/yourbuses' => 'welcome#yourbuses'

  get '/arrivals' => 'welcome#yourbuses_dropdown', as: :busesarriving

  get '/selection' => 'selections#new'

  root 'welcome#home'

  resources :stations

end

app/models/selection.rb
class Selection < ActiveRecord::Base
end

app/models/station.rb
class Station < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/selections_controller.rb
class SelectionsController < ApplicationController
  before_action :set_selection, only: [:show, :edit, :update, :destroy]

  # GET /selections
  # GET /selections.json
  def index
    @selections = Selection.all
  end

  # GET /selections/1
  # GET /selections/1.json
  def show
  end

  # GET /selections/new
  def new
    @selection = Selection.new
  end

  # GET /selections/1/edit
  def edit
  end

  # POST /selections
  # POST /selections.json
  def create

      @selection = Selection.new(selection_params)
      respond_to do |format|
     if @selection.save

       format.html { redirect_to busesarriving_path, notice: 'Selection was successfully created.' }
       format.json { render action: 'show', status: :created, location: @selection }

      else
       format.html { render action: 'new' }
       format.json { render json: @selection.errors, status: :unprocessable_entity }
      end
end
end

  # PATCH/PUT /selections/1
  # PATCH/PUT /selections/1.json
  def update
    respond_to do |format|
      if @selection.update(selection_params)
        format.html { redirect_to @selection, notice: 'Selection was successfully updated.' }
        format.json { render :show, status: :ok, location: @selection }
      else
        format.html { render :edit }
        format.json { render json: @selection.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /selections/1
  # DELETE /selections/1.json
  def destroy
    @selection.destroy
    respond_to do |format|
      format.html { redirect_to selections_url, notice: 'Selection was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_selection
      @selection = Selection.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def selection_params
      params.require(:selection).permit(:station_name)
    end
end

app/controllers/stations_controller.rb
class StationsController < ApplicationController
  before_action :set_station, only: [:show, :edit, :update, :destroy]

  # GET /stations
  # GET /stations.json
  def index
    @stations = Station.all
  end

  # GET /stations/1
  # GET /stations/1.json
  def show
  end

  # GET /stations/new
  def new
    @station = Station.new
  end

  # GET /stations/1/edit
  def edit
  end

  # POST /stations
  # POST /stations.json
  def create
    @station = Station.new(station_params)

    respond_to do |format|
      if @station.save
        format.html { redirect_to @station, notice: 'Station was successfully created.' }
        format.json { render :show, status: :created, location: @station }
      else
        format.html { render :new }
        format.json { render json: @station.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stations/1
  # PATCH/PUT /stations/1.json
  def update
    respond_to do |format|
      if @station.update(station_params)
        format.html { redirect_to @station, notice: 'Station was successfully updated.' }
        format.json { render :show, status: :ok, location: @station }
      else
        format.html { render :edit }
        format.json { render json: @station.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stations/1
  # DELETE /stations/1.json
  def destroy
    @station.destroy
    respond_to do |format|
      format.html { redirect_to stations_url, notice: 'Station was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_station
      @station = Station.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def station_params
      params.require(:station).permit(:name)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	include ApplicationHelper

	require 'open-uri'
	require 'json'



	def home
	end



	def radioselect
		@stations = ["North Springs", "Hamilton E. Holmes", "Lindbergh", "Midtown", "Georgia State", "Reynoldstown/Inman Park", "Dunwoody", "Lenox", "Sandy Springs", "Medical Center", "Doraville", "Chamblee", "Brookhaven/Oglethorpe", "Arts Center", "North Avenue", "Civic Center", "Ashby", "Peachtree Center", "Vine City", "West End", "Airport", "College Park", "East Point", "Philips Arena/CNN Center", "Garnett", "West Lake", "Bankhead", "Oakland City", "Lakewood/Ft. McPherson", "King Memorial", "Avondale", "East Lake", "Kensington", "Decatur", "Indian Creek", "Edgewood/Candler Park", "Inman Park/Reynoldstown", "Buckhead"]
		@stations = @stations.sort_by{|item| item.downcase}
	end

 
	def yourbuses
		@station = params[:station]
		@results = JSON.parse(open("http://developer.itsmarta.com/BRDRestService/BRDRestService.svc/GetAllBus").read)
		hash_and_msg_generator(@results, @station)
		
	end



	def yourbuses_dropdown
		yourstation = Selection.last
		@selection = yourstation.station_name
		@results = JSON.parse(open("http://developer.itsmarta.com/BRDRestService/BRDRestService.svc/GetAllBus").read)
		hash_and_msg_generator(@results, @selection)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper

 
	def hash_and_msg_generator(results, station)
		
		@message = ""
		@buses = {}
		results.each do |result|
		if result["TIMEPOINT"].include? station
			@buses[result["ROUTE"]] = result["VEHICLE"]
		end
	end

		if @buses.count == 0
			@message = "Sorry, it's gonna be a while."
			elsif @buses.count == 1
			@message = "A bus is on it's way!"
			elsif @buses.count > 1
			@message = "These buses will be coming soon:"
			else
			@message = "Oops...I think there was a slight error."
		end

end

end

app/helpers/selections_helper.rb
module SelectionsHelper
end

app/helpers/stations_helper.rb
module StationsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "MartaApp" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">MARTA TRANSPORT</a>
          <div class="container nav-collapse">
            <ul class="nav">
              <li><%= link_to "HOME", "/home"  %></li>
              <li><%= link_to "STATION", "/choosestation"  %></li>
              <li><%= link_to "SELECTION", "/selection"  %></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">
        <div class="row">
          <div class="span9">
            <%= bootstrap_flash %>
            <%= yield %>
          </div>
          <div class="span3">
            <div class="well sidebar-nav">
              <h3>Sidebar</h3>
              <ul class="nav nav-list">
                <li class="nav-header">Other Things</li>
                <li><%= link_to "HOME", "/home"  %></li>
                <li><%= link_to "STATION", "/choosestation"  %></li>
                <li><%= link_to "SELECTION", "/selection"  %></li>
              </ul>
            </div><!--/.well -->
          </div><!--/span-->
        </div><!--/row-->

      <footer>
        <p>&copy; Littlejohn 2014</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/selections/_form.html.erb
<%= form_for @selection, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :station_name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :station_name, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                selections_path, :class => 'btn' %>
  </div>
<% end %>

app/views/selections/edit.html.erb
<%- model_class = Selection -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/selections/index.html.erb
<%- model_class = Selection -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:station_name) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @selections.each do |selection| %>
      <tr>
        <td><%= link_to selection.id, selection_path(selection) %></td>
        <td><%= selection.station_name %></td>
        <td><%=l selection.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_selection_path(selection), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      selection_path(selection),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_selection_path,
            :class => 'btn btn-primary' %>

app/views/selections/new.html.erb
<%- model_class = Selection -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/selections/show.html.erb
<%- model_class = Selection -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:station_name) %>:</strong></dt>
  <dd><%= @selection.station_name %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              selections_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_selection_path(@selection), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              selection_path(@selection),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>

app/views/stations/_form.html.erb
<%= form_for @station, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                stations_path, :class => 'btn' %>
  </div>
<% end %>

app/views/stations/edit.html.erb
<%- model_class = Station -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/stations/index.html.erb
<%- model_class = Station -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @stations.each do |station| %>
      <tr>
        <td><%= link_to station.id, station_path(station) %></td>
        <td><%= station.name %></td>
        <td><%=l station.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_station_path(station), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      station_path(station),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_station_path,
            :class => 'btn btn-primary' %>

app/views/stations/new.html.erb
<%- model_class = Station -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/stations/show.html.erb
<%- model_class = Station -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @station.name %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              stations_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_station_path(@station), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              station_path(@station),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>

app/views/welcome/home.html.erb
<center><h1> WELCOME   TO   MARTA</h1></center>

app/views/welcome/radioselect.html.erb
<div class="scroll choose-a-station">
<h2 class="orange-text">Choose a Station!</h2>
<p><b>Which MARTA Station Are You At?</b></p>
</div>

 

<div class="radios">
<%= form_tag("/welcome/yourbuses", method: "get") do %>
<%= label_tag(:station, " " ) %>
<br />
<% @stations.each do |s| %>

<%= radio_button_tag(:station, s) %> <%= s %><br />
<% end %>
<%= submit_tag 'Check for buses!', :class=>'btn submit-button' %>
<% end %>
</div>

app/views/welcome/yourbuses.html.erb
<h3>
You are at: <%= @station %> Station.
</h3>

<div>
	<%= @message %>
</div>
<br />
<% @buses.each do |route, vehicle| %>

<div>
	Route: <%= route %><br />
	Vehicle: <%= vehicle %><br />
</div>

<hr />
<% end %>

app/views/welcome/yourbuses_dropdown.html.erb
<!--
This is the sister-page of yourbuses.html.erb
That one handles the results from the radio button choice,
this one handles the results from the dropdown menu choice.
-->

<h3>
You are at: <%= @selection %> Station.
</h3>

 

<div>
<%= @message %>
</div>
<br />
<% @buses.each do |route, vehicle| %>
<div>

Route: <%= route %><br />
Vehicle: <%= vehicle %><br />
</div>
<hr />
<% end %>